import random

from evolution.coordinator_settings import FOCUSED_GROUNDING_EXPERIMENT

from evolution.mixins.coordinator_task_generation_mixin import CoordinatorTaskGenerationMixin
from evolution.mixins.coordinator_task_scoring_mixin import CoordinatorTaskScoringMixin

class CoordinatorTaskMixin(CoordinatorTaskGenerationMixin, CoordinatorTaskScoringMixin):
    pass
